# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lee's Tech Blog
email: duy@dwork.vn
description: > # this means to ignore newlines until "baseurl:"
  Hope you get this.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://duyleekun.github.io" # the base hostname & protocol for your site
twitter_username: duyleekun
github_username:  duyleekun

# Build settings
markdown: kramdown
